// AUTO-GENERATED by triage-curator — do not edit by hand.
// Regenerate by re-running /triage-curator. Hand edits are clobbered.
//
// A method invoked on a chained receiver — typically `new X(...).method(...)` or `factory().method(...)` — where Ariadne records callers (diagnosis 'callers-in-registry-unresolved') but every call ref has receiver_kind 'call_chain' and a name_resolution failure 'name_not_in_scope'. Triggered for typeorm SubjectExecutor.ts:682 calling ClosureSubjectExecutor.remove via `await new ClosureSubjectExecutor(this.queryRunner).remove(subjects)`.

import type { EnrichedEntryPoint } from "@ariadnejs/types";
import type { FileLinesReader } from "../auto_classify_types";

export function check_constructor_instance_method_resolution(
  entry_point: EnrichedEntryPoint,
  read_file_lines: FileLinesReader,
): boolean {
  void read_file_lines;
  const check_0 = entry_point.diagnostics.diagnosis === "callers-in-registry-unresolved";
  const check_1 = entry_point.diagnostics.ariadne_call_refs.some((r) => r.receiver_kind === "call_chain");
  const check_2 = entry_point.diagnostics.ariadne_call_refs.some((r) => r.resolution_failure !== null && r.resolution_failure.reason === "name_not_in_scope");
  return check_0 && check_1 && check_2;
}
