// AUTO-GENERATED by triage-curator — do not edit by hand.
// Regenerate by re-running /triage-curator. Hand edits are clobbered.
//
// JavaScript instance method that is overridden in a subclass (or calls super) and invoked through `this.<method>(...)` in subclasses that `extends` the defining class. Ariadne's JS tree-sitter query does not capture `extends_clause` (ClassDefinition.extends is always empty for JS classes), so the resolver cannot connect the subclass receiver's `this` back to the inherited method on the parent. The entry_point therefore has diagnosis `callers-not-in-registry`, zero `ariadne_call_refs`, and grep evidence of real `this.<name>()` / `super.<name>()` call sites in sibling lib/ files. Root-caused by TASK-202 (JS class extends not captured).

import type { EnrichedEntryPoint } from "@ariadnejs/types";
import type { FileLinesReader } from "../auto_classify_types";

function detect_language(file_path: string): string | null {
  if (file_path.endsWith(".ts") || file_path.endsWith(".tsx")) return "typescript";
  if (file_path.endsWith(".js") || file_path.endsWith(".jsx")) return "javascript";
  if (file_path.endsWith(".py")) return "python";
  if (file_path.endsWith(".rs")) return "rust";
  return null;
}

export function check_callers_not_in_registry_unclassified(
  entry_point: EnrichedEntryPoint,
  read_file_lines: FileLinesReader,
): boolean {
  void read_file_lines;
  const check_0 = detect_language(entry_point.file_path) === "javascript";
  const check_1 = entry_point.diagnostics.diagnosis === "callers-not-in-registry";
  const check_2 = entry_point.diagnostics.ariadne_call_refs.length <= 0;
  const check_3 = (() => { const pattern = new RegExp("^\\s*(this|super)\\.[A-Za-z_][A-Za-z0-9_]*\\s*\\("); return entry_point.diagnostics.grep_call_sites.some((h) => pattern.test(h.content)); })();
  return check_0 && check_1 && check_2 && check_3;
}
