// AUTO-GENERATED by triage-curator — do not edit by hand.
// Regenerate by re-running /triage-curator. Hand edits are clobbered.
//
// JavaScript class constructors exported via the CommonJS `module.exports = ClassName` default-export idiom. Grep for the literal entry_point name `constructor` finds nothing (diagnosis: `no-textual-callers`) because real callers invoke `new ClassName(...)` through a `require('./mod')` binding, not the `constructor` keyword. Ariadne does not walk the `new (require(path))()` chain back to the exported class's constructor, so the definition appears to have zero inbound callers. Narrow to language=javascript, entry_point name=constructor, no-textual-callers diagnosis, and zero resolved call refs.

import type { EnrichedEntryPoint } from "@ariadnejs/types";
import type { FileLinesReader } from "../auto_classify_types";
import { detect_language } from "../extract_entry_point_diagnostics";

export function check_module_exports_class_constructor(
  entry_point: EnrichedEntryPoint,
  read_file_lines: FileLinesReader,
): boolean {
  void read_file_lines;
  const check_0 = detect_language(entry_point.file_path) === "javascript";
  const check_1 = new RegExp("^constructor$").test(entry_point.name);
  const check_2 = entry_point.diagnostics.diagnosis === "no-textual-callers";
  const check_3 = entry_point.diagnostics.ariadne_call_refs.length <= 0;
  return check_0 && check_1 && check_2 && check_3;
}
