// AUTO-GENERATED by triage-curator — do not edit by hand.
// Regenerate by re-running /triage-curator. Hand edits are clobbered.
//
// TypeScript method invoked through an `as`-cast receiver (e.g. `(factory as {componentReplaced?: (id: string) => void}).componentReplaced?.(...)`). At least one inbound call reference has receiver_kind=type_cast and the entry_point's diagnosis is callers-in-registry-unresolved, indicating Ariadne saw the call sites but cannot resolve the concrete class through the cast — typically because the cast target is an inline anonymous structural object type literal.

import type { EnrichedEntryPoint } from "@ariadnejs/types";
import type { FileLinesReader } from "../auto_classify_types";

function detect_language(file_path: string): string | null {
  if (file_path.endsWith(".ts") || file_path.endsWith(".tsx")) return "typescript";
  if (file_path.endsWith(".js") || file_path.endsWith(".jsx")) return "javascript";
  if (file_path.endsWith(".py")) return "python";
  if (file_path.endsWith(".rs")) return "rust";
  return null;
}

export function check_dynamic_cast_structural_type_dispatch(
  entry_point: EnrichedEntryPoint,
  read_file_lines: FileLinesReader,
): boolean {
  void read_file_lines;
  const check_0 = detect_language(entry_point.file_path) === "typescript";
  const check_1 = entry_point.diagnostics.ariadne_call_refs.some((r) => r.receiver_kind === "type_cast");
  const check_2 = entry_point.diagnostics.diagnosis === "callers-in-registry-unresolved";
  return check_0 && check_1 && check_2;
}
