// AUTO-GENERATED by triage-curator — do not edit by hand.
// Regenerate by re-running /triage-curator. Hand edits are clobbered.
//
// Python framework-invoked dunder methods (`__str__`, `__repr__`, `__eq__`,
// iteration / context-manager protocols, etc.) are called by the Python
// runtime, not by user code. The traceable subset (`__init__`, `__call__`,
// `__new__`) remains an entry point and is excluded here. Replaces the old
// hardcoded `filter_entry_points.python.ts` list with a registry-driven rule.

import type { EnrichedEntryPoint } from "@ariadnejs/types";
import type { FileLinesReader } from "../auto_classify_types";

const TRACEABLE_DUNDERS: ReadonlySet<string> = new Set([
  "__init__",
  "__call__",
  "__new__",
]);

function is_dunder_method(name: string): boolean {
  return name.length > 4 && name.startsWith("__") && name.endsWith("__");
}

export function check_py_dunder_protocol(
  entry_point: EnrichedEntryPoint,
  read_file_lines: FileLinesReader,
): boolean {
  void read_file_lines;
  if (!entry_point.file_path.endsWith(".py")) return false;
  if (entry_point.kind !== "method") return false;
  if (TRACEABLE_DUNDERS.has(entry_point.name)) return false;
  return is_dunder_method(entry_point.name);
}
