// AUTO-GENERATED by triage-curator — do not edit by hand.
// Regenerate by re-running /triage-curator. Hand edits are clobbered.
//
// Function defined as a named function expression assigned to a namespace property (`FBL.DomplateLoop = function DomplateLoop() {}`), then aliased to a local variable in the same file (`var DomplateLoop = FBL.DomplateLoop;`) and invoked through the alias (`new DomplateLoop()`). Ariadne reports zero call references for the function even though grep finds the literal call site in the same indexed file. The classifier fires only when the diagnosis is `callers-not-in-registry`, no inbound call refs were produced, and every grep hit lives in the same file as the definition — a tight intra-file pattern that distinguishes this group from the broad `callers-outside-scope-strict-grep-evidence` (which permits callers in other files). Scoped to JavaScript: the only observed entry_point is in a `.js` file (`vendor/firebug-lite/src/firebug-lite-debug.js`); a TypeScript variant would be a separate group_id when corpus evidence appears.

import type { EnrichedEntryPoint } from "../../entry_point_types.js";
import type { FileLinesReader } from "../types.js";

function detect_language(file_path: string): string | null {
  if (file_path.endsWith(".ts") || file_path.endsWith(".tsx")) return "typescript";
  if (file_path.endsWith(".js") || file_path.endsWith(".jsx")) return "javascript";
  if (file_path.endsWith(".py")) return "python";
  if (file_path.endsWith(".rs")) return "rust";
  return null;
}

export function check_property_alias_intra_file_call(
  entry_point: EnrichedEntryPoint,
  read_file_lines: FileLinesReader,
): boolean {
  void read_file_lines;
  const check_0 = detect_language(entry_point.file_path) === "javascript";
  const check_1 = entry_point.diagnostics.diagnosis === "callers-not-in-registry";
  const check_2 = entry_point.diagnostics.ariadne_call_refs.length <= 0;
  const check_3 = (entry_point.diagnostics.grep_call_sites.length > 0 && entry_point.diagnostics.grep_call_sites.every((h) => h.file_path === entry_point.file_path)) === true;
  return check_0 && check_1 && check_2 && check_3;
}
