// AUTO-GENERATED by triage-curator — do not edit by hand.
// Regenerate by re-running /triage-curator. Hand edits are clobbered.
//
// Functions (including nested anonymous lambdas) defined inside files in the prisma fill-plugin/fillers/ directory. These files are referenced exclusively via path.join(__dirname, 'fillers', '<name>.ts') string arguments passed to esbuild's `imports` and `globals` injection fields in fillPlugin.ts. There is no source-level import statement targeting these files, so every top-level export and every nested function inside them appears unreachable to a static call graph. The directory itself acts as the discriminator — it contains only polyfill targets registered via the build plugin's dynamic file-path injection mechanism.

import type { EnrichedEntryPoint } from "@ariadnejs/types";
import type { FileLinesReader } from "../auto_classify_types";

export function check_dynamic_runtime_injection(
  entry_point: EnrichedEntryPoint,
  read_file_lines: FileLinesReader,
): boolean {
  void read_file_lines;
  const check_0 = new RegExp("/fill-plugin/fillers/[^/]+\\.(ts|tsx|js|jsx|mjs|cjs)$").test(entry_point.file_path);
  return check_0;
}
