// AUTO-GENERATED by triage-curator — do not edit by hand.
// Regenerate by re-running /triage-curator. Hand edits are clobbered.
//
// JavaScript function whose definition is attached to a module-prototype object by direct property assignment (e.g. `app.path = function path() { return this.parent ? this.parent.path() + this.mountpath : ''; }` at lib/application.js:399, where `var app = exports = module.exports = {}` at lib/application.js:40). The function's body dispatches through `this` (here `this.parent.path()` — a recursive call via a `this`-rooted field access). Ariadne records the inbound call reference with `receiver_kind: self_keyword` but `resolve_keyword_base` cannot find an enclosing class scope (the prototype object is a plain literal, not a class), so the call fails with `resolution_failure.reason: no_enclosing_class_scope` and the definition surfaces as unreached even though the real caller exists on line 401.

import type { EnrichedEntryPoint } from "@ariadnejs/types";
import type { FileLinesReader } from "../auto_classify_types";

function detect_language(file_path: string): string | null {
  if (file_path.endsWith(".ts") || file_path.endsWith(".tsx")) return "typescript";
  if (file_path.endsWith(".js") || file_path.endsWith(".jsx")) return "javascript";
  if (file_path.endsWith(".py")) return "python";
  if (file_path.endsWith(".rs")) return "rust";
  return null;
}

export function check_dynamic_method_dispatch(
  entry_point: EnrichedEntryPoint,
  read_file_lines: FileLinesReader,
): boolean {
  void read_file_lines;
  const check_0 = detect_language(entry_point.file_path) === "javascript";
  const check_1 = entry_point.diagnostics.ariadne_call_refs.some((r) => r.receiver_kind === "self_keyword");
  const check_2 = entry_point.diagnostics.ariadne_call_refs.some((r) => r.resolution_failure !== null && r.resolution_failure.reason === "no_enclosing_class_scope");
  const check_3 = entry_point.diagnostics.diagnosis === "callers-in-registry-unresolved";
  return check_0 && check_1 && check_2 && check_3;
}
