// AUTO-GENERATED by triage-curator — do not edit by hand.
// Regenerate by re-running /triage-curator. Hand edits are clobbered.
//
// Plain-JavaScript method calls where the receiver type is present lexically (parameter, `this`, local identifier) but Ariadne's resolver cannot carry the type across the reference. Each matching entry_point has at least one `ariadne_call_refs[i]` whose `resolution_failure.reason` is one of `method_not_on_type`, `name_not_in_scope`, or `class_definition_not_found` — the resolver enumerated a candidate call-ref but failed to bind it to the definition. Strictly narrower than `callers-outside-scope-grep-evidence` (adds language=javascript + the in-registry-unresolved diagnosis) and complementary to the sibling group `receiver-type-unknown` (which requires `callers-not-in-registry` + empty refs). Also disjoint from F1 `aliased-receiver-type-lost`, which keys on `resolution_failure_reason_eq=receiver_type_unknown` — a reason that does not appear in this group's entries.

import type { EnrichedEntryPoint } from "@ariadnejs/types";
import type { FileLinesReader } from "../auto_classify_types";

function detect_language(file_path: string): string | null {
  if (file_path.endsWith(".ts") || file_path.endsWith(".tsx")) return "typescript";
  if (file_path.endsWith(".js") || file_path.endsWith(".jsx")) return "javascript";
  if (file_path.endsWith(".py")) return "python";
  if (file_path.endsWith(".rs")) return "rust";
  return null;
}

export function check_unresolved_receiver_type(
  entry_point: EnrichedEntryPoint,
  read_file_lines: FileLinesReader,
): boolean {
  void read_file_lines;
  const check_0 = detect_language(entry_point.file_path) === "javascript";
  const check_1 = entry_point.diagnostics.diagnosis === "callers-in-registry-unresolved";
  const check_2 = entry_point.diagnostics.ariadne_call_refs.length >= 1;
  return check_0 && check_1 && check_2;
}
