// AUTO-GENERATED by triage-curator — do not edit by hand.
// Regenerate by re-running /triage-curator. Hand edits are clobbered.
//
// ECMAScript private class field methods (#name) on TS/JS classes whose call sites this.#method() are not captured by the tree-sitter query. The class-body capture for definitions matches private_property_identifier, but the call_expression query for instance method calls only matches property_identifier, so this.#method() invocations never produce @reference.call captures.

import type { EnrichedEntryPoint } from "@ariadnejs/types";
import type { FileLinesReader } from "../auto_classify_types";

export function check_private_field_method_resolution(
  entry_point: EnrichedEntryPoint,
  read_file_lines: FileLinesReader,
): boolean {
  void read_file_lines;
  const check_0 = new RegExp("^#").test(entry_point.name);
  const check_1 = new RegExp("\\.(ts|tsx|js|jsx|mjs|cjs)$").test(entry_point.file_path);
  return check_0 && check_1;
}
