// AUTO-GENERATED by triage-curator — do not edit by hand.
// Regenerate by re-running /triage-curator. Hand edits are clobbered.
//
// JavaScript function expressions defined as values of object-literal property pairs (`key: function() {...}`) or prototype assignments are extracted by Ariadne with `name = '<anonymous>'`. Because grep is keyed on the entry_point name, no textual callers are ever found (`diagnosis = no-textual-callers`), and `this`-qualified intra-object dispatch (`this.sendRequest()`) plus property-reference callback registration (`setTimeout(this.sendRequest, 10)`) cannot be resolved. The triple `language=javascript` AND `name=<anonymous>` AND `diagnosis=no-textual-callers` discriminates the pattern: a truly unreachable anonymous function (e.g. an unused IIFE-style expression) is exceedingly rare in real code, while `key: function() {}` is the canonical pre-ES6 module/object pattern and the dominant shape seen in vendored libraries such as firebug-lite.

import type { EnrichedEntryPoint } from "@ariadnejs/types";
import type { FileLinesReader } from "../auto_classify_types";
import { detect_language } from "../extract_entry_point_diagnostics";

export function check_this_object_method_dispatch(
  entry_point: EnrichedEntryPoint,
  read_file_lines: FileLinesReader,
): boolean {
  void read_file_lines;
  const check_0 = detect_language(entry_point.file_path) === "javascript";
  const check_1 = new RegExp("^<anonymous>$").test(entry_point.name);
  const check_2 = entry_point.diagnostics.diagnosis === "no-textual-callers";
  return check_0 && check_1 && check_2;
}
