// AUTO-GENERATED by triage-curator — do not edit by hand.
// Regenerate by re-running /triage-curator. Hand edits are clobbered.
//
// Anonymous JavaScript function expression (name '<anonymous>') passed as an inline callback argument to a higher-order method (jQuery's `this.each(...)`) whose implementation dispatches it via `callback.call(obj[i], i, obj[i])`. Ariadne's resolver cannot trace the function value from the argument position through the renamed parameter to the `.call(...)` invocation, so the lambda has zero resolved inbound callers and surfaces as an entry point. Discriminator: anonymous JS function with no resolved callers — in JavaScript, such functions are always callbacks, event handlers, or IIFEs rather than genuine unreachable entries.

import type { EnrichedEntryPoint } from "@ariadnejs/types";
import type { FileLinesReader } from "../auto_classify_types";

function detect_language(file_path: string): string | null {
  if (file_path.endsWith(".ts") || file_path.endsWith(".tsx")) return "typescript";
  if (file_path.endsWith(".js") || file_path.endsWith(".jsx")) return "javascript";
  if (file_path.endsWith(".py")) return "python";
  if (file_path.endsWith(".rs")) return "rust";
  return null;
}

export function check_call_apply_dispatch(
  entry_point: EnrichedEntryPoint,
  read_file_lines: FileLinesReader,
): boolean {
  void read_file_lines;
  const check_0 = detect_language(entry_point.file_path) === "javascript";
  const check_1 = new RegExp("^<anonymous>$").test(entry_point.name);
  const check_2 = entry_point.diagnostics.ariadne_call_refs.length <= 0;
  return check_0 && check_1 && check_2;
}
