// AUTO-GENERATED by triage-curator — do not edit by hand.
// Regenerate by re-running /triage-curator. Hand edits are clobbered.
//
// Function definition whose value flows through an object-property store + destructure before being invoked as a bare identifier. All ariadne_call_refs fail with name_not_in_scope and receiver_kind=none, while tree-sitter already captured reference.call at the grep hits — ruling out syntactic-extraction gaps and narrowing to a cross-file-flow resolver miss. Concretely: `const extractValue = (...args) => ...; return { extractValue, ... }` later destructured as `const { extractValue } = param; extractValue(...params)` in nestjs rpc-context-creator.ts:238.

import type { EnrichedEntryPoint } from "@ariadnejs/types";
import type { FileLinesReader } from "../auto_classify_types";

function detect_language(file_path: string): string | null {
  if (file_path.endsWith(".ts") || file_path.endsWith(".tsx")) return "typescript";
  if (file_path.endsWith(".js") || file_path.endsWith(".jsx")) return "javascript";
  if (file_path.endsWith(".py")) return "python";
  if (file_path.endsWith(".rs")) return "rust";
  return null;
}

export function check_stored_callback_via_object_property(
  entry_point: EnrichedEntryPoint,
  read_file_lines: FileLinesReader,
): boolean {
  void read_file_lines;
  const check_0 = detect_language(entry_point.file_path) === "typescript";
  const check_1 = entry_point.diagnostics.diagnosis === "callers-in-registry-unresolved";
  const check_2 = entry_point.diagnostics.ariadne_call_refs.some((r) => r.resolution_failure !== null && r.resolution_failure.reason === "name_not_in_scope");
  const check_3 = entry_point.diagnostics.ariadne_call_refs.some((r) => r.receiver_kind === "none");
  const check_4 = entry_point.diagnostics.grep_call_sites.some((h) => h.captures.includes("reference.call"));
  return check_0 && check_1 && check_2 && check_3 && check_4;
}
