// AUTO-GENERATED by triage-curator — do not edit by hand.
// Regenerate by re-running /triage-curator. Hand edits are clobbered.
//
// TypeScript method calls on a receiver typed via an aliased import (e.g. `import { ViewRef as InternalViewRef }`) where Ariadne cannot follow the import alias to the original class. Surfaces as a `type_cast` call-ref with `receiver_type_unknown`, paired with grep evidence of an `as <AliasedType<...>>` cast pattern in the call sites.

import type { EnrichedEntryPoint } from "@ariadnejs/types";
import type { FileLinesReader } from "../auto_classify_types";

function detect_language(file_path: string): string | null {
  if (file_path.endsWith(".ts") || file_path.endsWith(".tsx")) return "typescript";
  if (file_path.endsWith(".js") || file_path.endsWith(".jsx")) return "javascript";
  if (file_path.endsWith(".py")) return "python";
  if (file_path.endsWith(".rs")) return "rust";
  return null;
}

export function check_aliased_import_method_dispatch(
  entry_point: EnrichedEntryPoint,
  read_file_lines: FileLinesReader,
): boolean {
  void read_file_lines;
  const check_0 = detect_language(entry_point.file_path) === "typescript";
  const check_1 = entry_point.diagnostics.diagnosis === "callers-in-registry-unresolved";
  const check_2 = entry_point.diagnostics.ariadne_call_refs.some((r) => r.receiver_kind === "type_cast");
  const check_3 = entry_point.diagnostics.ariadne_call_refs.some((r) => r.resolution_failure !== null && r.resolution_failure.reason === "receiver_type_unknown");
  const check_4 = (() => { const pattern = new RegExp("\\bas\\s+[A-Z][A-Za-z0-9_]*\\s*<"); return entry_point.diagnostics.grep_call_sites.some((h) => pattern.test(h.content)); })();
  return check_0 && check_1 && check_2 && check_3 && check_4;
}
