// AUTO-GENERATED by triage-curator — do not edit by hand.
// Regenerate by re-running /triage-curator. Hand edits are clobbered.
//
// JavaScript named function expressions assigned to a `var` (e.g. `var Chrome = function Chrome(chrome) { ... }`) that are invoked intra-file via `new Chrome(...)`. The tree-sitter query fires `@reference.constructor`, so a CallReference exists, but the resolver fails at `constructor_lookup` with `name_not_in_scope` because the var-bound named-function-expression name is not registered as a constructible target in the enclosing script scope. Filtered to PascalCase names so the rule does not fire on lowercase function-valued vars.

import type { EnrichedEntryPoint } from "@ariadnejs/types";
import type { FileLinesReader } from "../auto_classify_types";

function detect_language(file_path: string): string | null {
  if (file_path.endsWith(".ts") || file_path.endsWith(".tsx")) return "typescript";
  if (file_path.endsWith(".js") || file_path.endsWith(".jsx")) return "javascript";
  if (file_path.endsWith(".py")) return "python";
  if (file_path.endsWith(".rs")) return "rust";
  return null;
}

export function check_constructor_call_resolution(
  entry_point: EnrichedEntryPoint,
  read_file_lines: FileLinesReader,
): boolean {
  void read_file_lines;
  const check_0 = detect_language(entry_point.file_path) === "javascript";
  const check_1 = entry_point.diagnostics.diagnosis === "callers-in-registry-unresolved";
  const check_2 = entry_point.diagnostics.ariadne_call_refs.some((r) => r.syntactic_features.is_new_expression === true);
  const check_3 = entry_point.diagnostics.ariadne_call_refs.some((r) => r.resolution_failure !== null && r.resolution_failure.reason === "name_not_in_scope");
  const check_4 = new RegExp("^[A-Z][A-Za-z0-9_$]*$").test(entry_point.name);
  return check_0 && check_1 && check_2 && check_3 && check_4;
}
