// AUTO-GENERATED by triage-curator — do not edit by hand.
// Regenerate by re-running /triage-curator. Hand edits are clobbered.
//
// TypeScript class constructors with zero resolved inbound call references. `new ClassName(...)` sites are captured by tree-sitter (`@reference.constructor` fires at the grep hits) but the resolver does not link them back to the class's constructor member, leaving the constructor with an empty `ariadne_call_refs`. Classifies as the existing `constructor-new-expression` false-positive pattern.

import type { EnrichedEntryPoint } from "@ariadnejs/types";
import type { FileLinesReader } from "../auto_classify_types";
import { detect_language } from "../extract_entry_point_diagnostics";

export function check_constructor_new_expression(
  entry_point: EnrichedEntryPoint,
  read_file_lines: FileLinesReader,
): boolean {
  void read_file_lines;
  const check_0 = detect_language(entry_point.file_path) === "typescript";
  const check_1 = new RegExp("^constructor$").test(entry_point.name);
  const check_2 = entry_point.diagnostics.ariadne_call_refs.length <= 0;
  return check_0 && check_1 && check_2;
}
