// AUTO-GENERATED by triage-curator — do not edit by hand.
// Regenerate by re-running /triage-curator. Hand edits are clobbered.
//
// Module-level helper function whose only textual references live inside its own file but Ariadne resolved zero callers. Targets the JS/TS shape where class-method bodies (static or instance) call a top-level free function declared with `function name(...)` at module scope — observed in prisma's helpers/compile/plugins/fill-plugin/fillers/buffer-small.ts where stringToBuffer / assertNumber / assertUnsigned / assertInteger / assertBounds / assertString / assertUint8Array / bufferPolyfillDoesNotImplement are each called dozens of times from within the BufferClass body but reported as entry points with zero callees. The combinator is structural: callers_count_at_most(0) ensures Ariadne sees no inbound calls; grep_hits_all_intra_file(true) ensures no external callers either; the negative-lookahead regex on `function ` ensures at least one grep hit is a call site (not the definition line itself), eliminating the genuinely-uncalled dead-code edge case.

import type { EnrichedEntryPoint } from "@ariadnejs/types";
import type { FileLinesReader } from "../auto_classify_types";

export function check_intra_file_call_not_resolved(
  entry_point: EnrichedEntryPoint,
  read_file_lines: FileLinesReader,
): boolean {
  void read_file_lines;
  const check_0 = entry_point.diagnostics.ariadne_call_refs.length <= 0;
  const check_1 = (entry_point.diagnostics.grep_call_sites.length > 0 && entry_point.diagnostics.grep_call_sites.every((h) => h.file_path === entry_point.file_path)) === true;
  const check_2 = (() => { const pattern = new RegExp("^(?!\\s*(?:export\\s+)?(?:async\\s+)?function\\s)."); return entry_point.diagnostics.grep_call_sites.some((h) => pattern.test(h.content)); })();
  return check_0 && check_1 && check_2;
}
