// AUTO-GENERATED by triage-curator — do not edit by hand.
// Regenerate by re-running /triage-curator. Hand edits are clobbered.
//
// Anonymous TypeScript functions whose only caller is a higher-order function that invokes its function-typed parameter. The static call graph cannot link the lambda back to the callee that calls it indirectly, and no textual caller exists because the function literal has no name to grep for. Diagnosis 'no-textual-callers' plus an anonymous name is the structural fingerprint.

import type { EnrichedEntryPoint } from "../../entry_point_types.js";
import type { FileLinesReader } from "../types.js";

function detect_language(file_path: string): string | null {
  if (file_path.endsWith(".ts") || file_path.endsWith(".tsx")) return "typescript";
  if (file_path.endsWith(".js") || file_path.endsWith(".jsx")) return "javascript";
  if (file_path.endsWith(".py")) return "python";
  if (file_path.endsWith(".rs")) return "rust";
  return null;
}

export function check_higher_order_function_callback(
  entry_point: EnrichedEntryPoint,
  read_file_lines: FileLinesReader,
): boolean {
  void read_file_lines;
  const check_0 = detect_language(entry_point.file_path) === "typescript";
  const check_1 = new RegExp("^<anonymous>$").test(entry_point.name);
  const check_2 = entry_point.diagnostics.diagnosis === "no-textual-callers";
  return check_0 && check_1 && check_2;
}
