import { describe, expect, it } from "vitest";
import * as ts from "typescript";

import {
  UnknownSignalCheckOpError,
  render_classifier,
} from "./render_classifier.js";
import type { BuiltinClassifierSpec, SignalCheck } from "./types.js";
import { SIGNAL_CHECK_OPS } from "./types.js";

function make_spec(overrides: Partial<BuiltinClassifierSpec> = {}): BuiltinClassifierSpec {
  return {
    function_name: "check_example",
    min_confidence: 0.9,
    combinator: "all",
    checks: [],
    positive_examples: [],
    negative_examples: [],
    description: "Example classifier",
    ...overrides,
  };
}

function assert_syntactically_valid(source: string): void {
  const { diagnostics = [] } = ts.transpileModule(source, {
    fileName: "check_example.ts",
    reportDiagnostics: true,
    compilerOptions: {
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.ESNext,
      isolatedModules: true,
      noEmit: true,
    },
  });
  if (diagnostics.length > 0) {
    const formatted = diagnostics
      .map((d) => ts.flattenDiagnosticMessageText(d.messageText, "\n"))
      .join("\n");
    throw new Error(`Syntactic diagnostics in generated source:\n${formatted}\n---\n${source}`);
  }
}

describe("render_classifier", () => {
  it("emits a header, imports, and function signature", () => {
    const src = render_classifier(
      make_spec({ description: "line one\nline two" }),
    );
    expect(src).toContain("// AUTO-GENERATED by triage-curator");
    expect(src).toContain("// line one");
    expect(src).toContain("// line two");
    expect(src).toContain("import type { EnrichedFunctionEntry } from \"../../types.js\"");
    expect(src).toContain("import type { FileLinesReader } from \"../types.js\"");
    expect(src).toContain("export function check_example(");
    expect(src).toContain("entry: EnrichedFunctionEntry,");
    expect(src).toContain("read_file_lines: FileLinesReader,");
    expect(src).toContain("): boolean {");
    assert_syntactically_valid(src);
  });

  it("empty checks + combinator='all' returns true (vacuous)", () => {
    const src = render_classifier(make_spec({ combinator: "all" }));
    expect(src).toContain("return true;");
    assert_syntactically_valid(src);
  });

  it("empty checks + combinator='any' returns false (vacuous)", () => {
    const src = render_classifier(make_spec({ combinator: "any" }));
    expect(src).toContain("return false;");
    assert_syntactically_valid(src);
  });

  it("combinator='all' folds checks with &&", () => {
    const src = render_classifier(
      make_spec({
        combinator: "all",
        checks: [
          { op: "diagnosis_eq", value: "no-textual-callers" },
          { op: "name_matches", pattern: "^handle_" },
        ],
      }),
    );
    expect(src).toContain("return check_0 && check_1;");
    assert_syntactically_valid(src);
  });

  it("combinator='any' folds checks with ||", () => {
    const src = render_classifier(
      make_spec({
        combinator: "any",
        checks: [
          { op: "name_matches", pattern: "^handle_" },
          { op: "name_matches", pattern: "^on_" },
        ],
      }),
    );
    expect(src).toContain("return check_0 || check_1;");
    assert_syntactically_valid(src);
  });

  it("is deterministic — same input produces byte-identical output", () => {
    const spec = make_spec({
      checks: [
        { op: "grep_line_regex", pattern: "\\bfoo\\b" },
        { op: "language_eq", value: "typescript" },
      ],
    });
    expect(render_classifier(spec)).toBe(render_classifier(spec));
  });

  it("throws UnknownSignalCheckOpError on an invalid op", () => {
    // JSON.parse returns `any`, so assigning to SignalCheck does not require a
    // cast — a clean way to synthesise an invalid-at-runtime union member for
    // the renderer to reject.
    const bogus: SignalCheck = JSON.parse("{\"op\":\"totally_not_real\"}");
    expect(() =>
      render_classifier(make_spec({ checks: [bogus] })),
    ).toThrowError(UnknownSignalCheckOpError);
  });

  it("SIGNAL_CHECK_OPS matches the union exhaustively (by test coverage below)", () => {
    // This is a soft cross-check: every op in the exported constant appears in
    // the per-op cases below, and every per-op case uses an op present in the constant.
    expect(new Set(SIGNAL_CHECK_OPS)).toEqual(
      new Set([
        "diagnosis_eq",
        "language_eq",
        "syntactic_feature_eq",
        "grep_line_regex",
        "decorator_matches",
        "has_capture_at_grep_hit",
        "missing_capture_at_grep_hit",
        "receiver_kind_eq",
        "resolution_failure_reason_eq",
        "callers_count_at_least",
        "callers_count_at_most",
        "file_path_matches",
        "name_matches",
      ]),
    );
  });

  describe("per-op translation — each produces syntactically valid source", () => {
    const cases: Array<{ label: string; check: SignalCheck; expect_substring: string }> = [
      {
        label: "diagnosis_eq",
        check: { op: "diagnosis_eq", value: "no-textual-callers" },
        expect_substring: "entry.diagnostics.diagnosis === \"no-textual-callers\"",
      },
      {
        label: "language_eq",
        check: { op: "language_eq", value: "python" },
        expect_substring: "detect_language(entry.file_path) === \"python\"",
      },
      {
        label: "syntactic_feature_eq",
        check: { op: "syntactic_feature_eq", name: "is_new_expression", value: true },
        expect_substring: "\"is_new_expression\"",
      },
      {
        label: "grep_line_regex",
        check: { op: "grep_line_regex", pattern: "\\bfoo\\b" },
        expect_substring: "new RegExp",
      },
      {
        label: "decorator_matches",
        check: { op: "decorator_matches", pattern: "@Component" },
        expect_substring: "extract_decorator_block(",
      },
      {
        label: "has_capture_at_grep_hit",
        check: {
          op: "has_capture_at_grep_hit",
          capture_name: "reference.constructor",
        },
        expect_substring: "h.captures.includes(\"reference.constructor\")",
      },
      {
        label: "missing_capture_at_grep_hit",
        check: {
          op: "missing_capture_at_grep_hit",
          capture_name: "reference.constructor",
        },
        expect_substring: "!h.captures.includes(\"reference.constructor\")",
      },
      {
        label: "receiver_kind_eq",
        check: { op: "receiver_kind_eq", value: "super" },
        expect_substring: "r.receiver_kind === \"super\"",
      },
      {
        label: "resolution_failure_reason_eq",
        check: { op: "resolution_failure_reason_eq", value: "name_not_in_scope" },
        expect_substring: "r.resolution_failure.reason === \"name_not_in_scope\"",
      },
      {
        label: "callers_count_at_least",
        check: { op: "callers_count_at_least", n: 3 },
        expect_substring: "ariadne_call_refs.length >= 3",
      },
      {
        label: "callers_count_at_most",
        check: { op: "callers_count_at_most", n: 0 },
        expect_substring: "ariadne_call_refs.length <= 0",
      },
      {
        label: "file_path_matches",
        check: { op: "file_path_matches", pattern: "\\.test\\.ts$" },
        expect_substring: "test(entry.file_path)",
      },
      {
        label: "name_matches",
        check: { op: "name_matches", pattern: "^handle_" },
        expect_substring: "test(entry.name)",
      },
    ];

    for (const { label, check, expect_substring } of cases) {
      it(label, () => {
        const src = render_classifier(make_spec({ checks: [check] }));
        expect(src).toContain(expect_substring);
        assert_syntactically_valid(src);
      });
    }
  });

  it("emits detect_language helper only when needed", () => {
    const without_helper = render_classifier(
      make_spec({ checks: [{ op: "name_matches", pattern: "x" }] }),
    );
    expect(without_helper).not.toContain("function detect_language");
    const with_helper = render_classifier(
      make_spec({ checks: [{ op: "language_eq", value: "rust" }] }),
    );
    expect(with_helper).toContain("function detect_language");
    assert_syntactically_valid(without_helper);
    assert_syntactically_valid(with_helper);
  });

  it("emits extract_decorator_block helper only when needed", () => {
    const without_helper = render_classifier(
      make_spec({ checks: [{ op: "name_matches", pattern: "x" }] }),
    );
    expect(without_helper).not.toContain("function extract_decorator_block");
    const with_helper = render_classifier(
      make_spec({ checks: [{ op: "decorator_matches", pattern: "@Foo" }] }),
    );
    expect(with_helper).toContain("function extract_decorator_block");
    assert_syntactically_valid(without_helper);
    assert_syntactically_valid(with_helper);
  });

  it("suppresses unused read_file_lines when no check uses it", () => {
    const src = render_classifier(
      make_spec({ checks: [{ op: "name_matches", pattern: "x" }] }),
    );
    expect(src).toContain("void read_file_lines;");
    assert_syntactically_valid(src);
  });

  it("does not suppress read_file_lines when decorator_matches uses it", () => {
    const src = render_classifier(
      make_spec({ checks: [{ op: "decorator_matches", pattern: "@Foo" }] }),
    );
    expect(src).not.toContain("void read_file_lines;");
    assert_syntactically_valid(src);
  });

  it("renders all ops together in a single classifier", () => {
    const all_ops: SignalCheck[] = [
      { op: "diagnosis_eq", value: "no-textual-callers" },
      { op: "language_eq", value: "typescript" },
      { op: "syntactic_feature_eq", name: "is_super_call", value: true },
      { op: "grep_line_regex", pattern: "foo" },
      { op: "decorator_matches", pattern: "@Bar" },
      { op: "has_capture_at_grep_hit", capture_name: "c" },
      { op: "missing_capture_at_grep_hit", capture_name: "c" },
      { op: "receiver_kind_eq", value: "object" },
      { op: "resolution_failure_reason_eq", value: "name_not_in_scope" },
      { op: "callers_count_at_least", n: 1 },
      { op: "callers_count_at_most", n: 5 },
      { op: "file_path_matches", pattern: "src/" },
      { op: "name_matches", pattern: "^foo" },
    ];
    const src = render_classifier(
      make_spec({ combinator: "any", checks: all_ops }),
    );
    assert_syntactically_valid(src);
    for (let i = 0; i < all_ops.length; i++) {
      expect(src).toContain(`const check_${i} = `);
    }
  });
});
