/**
 * Renders a BuiltinClassifierSpec into a complete TypeScript module body for
 * `packages/core/src/classify_entry_points/builtins/check_<group_id>.ts`.
 *
 * The renderer is pure, deterministic, and exhaustive over `SignalCheck.op`.
 * Unknown ops throw — the dispatcher treats a throw as a Step 4.5 authoring
 * failure and skips the registry upsert for that group.
 *
 * Regenerate by re-running `/triage-curator`; hand edits are clobbered.
 */

import type { BuiltinClassifierSpec, SignalCheck } from "./types.js";

export class UnknownSignalCheckOpError extends Error {
  constructor(op: string) {
    super(`Unknown SignalCheck op: ${op}`);
    this.name = "UnknownSignalCheckOpError";
  }
}

interface HelperRequirements {
  detect_language: boolean;
  extract_decorator_block: boolean;
  /** True if any check uses read_file_lines — prevents an unused-parameter warning. */
  uses_read_file_lines: boolean;
  /**
   * Regex patterns hoisted to module-level constants in render order. Each
   * `RE_<i>` is `new RegExp(pattern)` evaluated at module load, replacing the
   * per-call `new RegExp(...)` constructions across all check ops that read a
   * fixed pattern. Index = position in this array.
   */
  hoisted_patterns: string[];
}

export function render_classifier(spec: BuiltinClassifierSpec): string {
  const lines: string[] = [];
  const helpers: HelperRequirements = {
    detect_language: false,
    extract_decorator_block: false,
    uses_read_file_lines: false,
    hoisted_patterns: [],
  };

  const check_exprs = spec.checks.map((c) => render_check(c, helpers));

  lines.push(
    "// AUTO-GENERATED by triage-curator — do not edit by hand.",
    "// Regenerate by re-running /triage-curator. Hand edits are clobbered.",
    "//",
  );
  for (const desc_line of spec.description.split("\n")) {
    lines.push(`// ${desc_line}`);
  }
  lines.push("");
  lines.push("import type { EnrichedEntryPoint } from \"@ariadnejs/types\";");
  lines.push("import type { FileLinesReader } from \"../auto_classify_types\";");
  // `detect_language` is the canonical helper exported from the diagnostics
  // extractor in core. Importing it here (instead of inlining) keeps every
  // generated builtin aligned with its `.mjs` / `.cjs` widening — see
  // commit `da630f8b` for the dedup across skill consumers.
  if (helpers.detect_language) {
    lines.push(
      "import { detect_language } from \"../extract_entry_point_diagnostics\";",
    );
  }
  lines.push("");
  if (helpers.extract_decorator_block) {
    lines.push(
      "function extract_decorator_block(",
      "  lines: readonly string[],",
      "  start_line_1_based: number,",
      "): string {",
      "  const collected: string[] = [];",
      "  for (let i = start_line_1_based - 2; i >= 0; i--) {",
      "    const line = lines[i] ?? \"\";",
      "    const trimmed = line.trim();",
      "    if (trimmed.length === 0) continue;",
      "    if (trimmed.startsWith(\"@\") || trimmed.startsWith(\"#[\") || trimmed.startsWith(\"#![\")) {",
      "      collected.unshift(line);",
      "      continue;",
      "    }",
      "    break;",
      "  }",
      "  return collected.join(\"\\n\");",
      "}",
      "",
    );
  }

  // Module-level hoisted patterns. Compiling at module load (instead of on
  // every entry-point evaluation) saves ~25-50k `new RegExp(...)` allocations
  // per pipeline run on the largest fixtures.
  if (helpers.hoisted_patterns.length > 0) {
    for (let i = 0; i < helpers.hoisted_patterns.length; i++) {
      lines.push(`const RE_${i} = new RegExp(${helpers.hoisted_patterns[i]});`);
    }
    lines.push("");
  }

  lines.push(`export function ${spec.function_name}(`);
  lines.push("  entry_point: EnrichedEntryPoint,");
  lines.push("  read_file_lines: FileLinesReader,");
  lines.push("): boolean {");

  if (!helpers.uses_read_file_lines) {
    lines.push("  void read_file_lines;");
  }

  if (check_exprs.length === 0) {
    // Vacuous combinator: no checks means always matches for "all", never for "any".
    // An investigator spec with zero checks is a bug, but render shouldn't crash.
    const vacuous = spec.combinator === "all" ? "true" : "false";
    lines.push(`  return ${vacuous};`);
  } else {
    for (let i = 0; i < check_exprs.length; i++) {
      lines.push(`  const check_${i} = ${check_exprs[i]};`);
    }
    const joiner = spec.combinator === "all" ? " && " : " || ";
    const fold = check_exprs.map((_, i) => `check_${i}`).join(joiner);
    lines.push(`  return ${fold};`);
  }

  lines.push("}", "");

  return lines.join("\n");
}

function render_check(check: SignalCheck, helpers: HelperRequirements): string {
  switch (check.op) {
    case "diagnosis_eq":
      return `entry_point.diagnostics.diagnosis === ${JSON.stringify(check.value)}`;

    case "language_eq":
      helpers.detect_language = true;
      return `detect_language(entry_point.file_path) === ${JSON.stringify(check.value)}`;

    case "syntactic_feature_eq":
      // Feature names are a closed enum (SyntacticFeatureName) of valid identifiers
      // — emit direct property access for type safety.
      return (
        "entry_point.diagnostics.ariadne_call_refs.some((r) => " +
        `r.syntactic_features.${check.name} === ${JSON.stringify(check.value)})`
      );

    case "grep_line_regex": {
      const idx = helpers.hoisted_patterns.length;
      helpers.hoisted_patterns.push(JSON.stringify(check.pattern));
      return (
        `entry_point.diagnostics.grep_call_sites.some((h) => RE_${idx}.test(h.content))`
      );
    }

    case "decorator_matches": {
      helpers.extract_decorator_block = true;
      helpers.uses_read_file_lines = true;
      const idx = helpers.hoisted_patterns.length;
      helpers.hoisted_patterns.push(JSON.stringify(check.pattern));
      return (
        `RE_${idx}.test(extract_decorator_block(` +
        "read_file_lines(entry_point.file_path), entry_point.start_line))"
      );
    }

    case "has_capture_at_grep_hit":
      return (
        "entry_point.diagnostics.grep_call_sites.some((h) => " +
        `h.captures.includes(${JSON.stringify(check.capture_name)}))`
      );

    case "missing_capture_at_grep_hit":
      return (
        "entry_point.diagnostics.grep_call_sites.some((h) => " +
        `!h.captures.includes(${JSON.stringify(check.capture_name)}))`
      );

    case "receiver_kind_eq":
      return (
        "entry_point.diagnostics.ariadne_call_refs.some((r) => " +
        `r.receiver_kind === ${JSON.stringify(check.value)})`
      );

    case "resolution_failure_reason_eq":
      return (
        "entry_point.diagnostics.ariadne_call_refs.some((r) => " +
        `r.resolution_failure !== null && r.resolution_failure.reason === ${JSON.stringify(check.value)})`
      );

    case "callers_count_at_least":
      return `entry_point.diagnostics.ariadne_call_refs.length >= ${check.n}`;

    case "callers_count_at_most":
      return `entry_point.diagnostics.ariadne_call_refs.length <= ${check.n}`;

    case "file_path_matches": {
      const idx = helpers.hoisted_patterns.length;
      helpers.hoisted_patterns.push(JSON.stringify(check.pattern));
      return `RE_${idx}.test(entry_point.file_path)`;
    }

    case "name_matches": {
      const idx = helpers.hoisted_patterns.length;
      helpers.hoisted_patterns.push(JSON.stringify(check.pattern));
      return `RE_${idx}.test(entry_point.name)`;
    }

    case "grep_hits_all_intra_file": {
      const expected = check.value;
      return (
        "(entry_point.diagnostics.grep_call_sites.length > 0 && " +
        "entry_point.diagnostics.grep_call_sites.every((h) => h.file_path === entry_point.file_path)) " +
        `=== ${expected ? "true" : "false"}`
      );
    }

    case "grep_hit_neighbourhood_matches": {
      helpers.uses_read_file_lines = true;
      const idx = helpers.hoisted_patterns.length;
      helpers.hoisted_patterns.push(JSON.stringify(check.pattern));
      const window = check.window;
      return (
        "entry_point.diagnostics.grep_call_sites.some((h) => { " +
        "const lines = read_file_lines(h.file_path); " +
        `const start = Math.max(0, h.line - 1 - ${window}); ` +
        "for (let i = start; i < h.line - 1; i++) { " +
        `if (RE_${idx}.test(lines[i] ?? "")) return true; ` +
        "} return false; })"
      );
    }

    case "definition_feature_eq": {
      // Feature names are a closed enum (DefinitionFeatureName) of valid identifiers
      // — emit direct property access for type safety.
      return `entry_point.definition_features.${check.name} === ${check.value ? "true" : "false"}`;
    }

    case "accessor_kind_eq": {
      if (check.value === "none") {
        return "entry_point.definition_features.accessor_kind === null";
      }
      return `entry_point.definition_features.accessor_kind === ${JSON.stringify(check.value)}`;
    }

    case "has_unindexed_test_caller": {
      const expected = check.value;
      return (
        "(entry_point.diagnostics.grep_call_sites_unindexed_tests.length > 0) === " +
        `${expected ? "true" : "false"}`
      );
    }
  }
  const unreachable: never = check;
  throw new UnknownSignalCheckOpError(
    (unreachable as { op: string }).op ?? "<missing op>",
  );
}
