#!/usr/bin/env node
/**
 * Authoritative owner of the builtins-regen contract.
 *
 * Reads the full skill registry at
 * `.claude/skills/triage-entrypoints/known_issues/registry.json`, filters to
 * `status === "permanent" && classifier.kind !== "none"`, and writes:
 *
 *   1. `packages/core/src/classify_entry_points/permanent_data.ts` — the
 *      bundled permanent slice as a typed TypeScript module. The body is a
 *      deterministic JSON-formatted object literal so diffs stay stable
 *      across runs; tsc emits it into `dist/` as part of the normal build.
 *   2. `packages/core/src/classify_entry_points/builtins/index.ts` — the
 *      orchestrator's `BUILTIN_CHECKS` map. Re-rendered via
 *      `render_builtins_barrel` so the import header always tracks the
 *      registry's current `function_name` set.
 *
 * CI invokes `pnpm sync-permanent-rules` followed by `git diff --exit-code`
 * over the generated paths so a registry edit without a regen fails fast.
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

import {
  KNOWN_ISSUES_REGISTRY_SCHEMA_VERSION,
  parse_known_issues_registry_json,
  type KnownIssue,
  type KnownIssuesRegistryFile,
  type PredicateExpr,
} from "@ariadnejs/types";
import { render_builtins_barrel } from "../src/render/render_builtins_barrel.js";
import {
  get_core_builtins_barrel_path,
  get_permanent_slice_path,
  get_registry_file_path,
} from "../src/store/paths.js";

const PERMANENT_DATA_PATH = get_permanent_slice_path();
const BARREL_PATH = get_core_builtins_barrel_path();

interface SyncResult {
  permanent_count: number;
  builtin_count: number;
}

/**
 * Regenerate the permanent slice TS module and the builtins barrel from the
 * full skill registry. Returns counts of what was written so callers can log.
 *
 * The barrel contains every `kind: "builtin"` rule's function regardless of
 * `status` — wip-status builtins must still resolve in `BUILTIN_CHECKS` when
 * the skill runs the full registry against `enrich_call_graph`. The slice
 * (`permanent_data.ts`) gates which rules ship in core's default flow.
 */
export async function sync_permanent_rules(): Promise<SyncResult> {
  const raw = await fs.readFile(get_registry_file_path(), "utf8");
  const registry = parse_known_issues_registry_json(raw);
  const permanent = filter_permanent_slice(registry);
  await write_permanent_data(permanent);
  await write_builtins_barrel(registry);
  return {
    permanent_count: permanent.length,
    builtin_count: registry.filter((r) => r.classifier.kind === "builtin").length,
  };
}

function filter_permanent_slice(registry: readonly KnownIssue[]): KnownIssue[] {
  return registry.filter(
    (issue) => issue.status === "permanent" && issue.classifier.kind !== "none",
  );
}

/**
 * Render the permanent slice as a typed TS module. The body is a
 * deterministic JSON-formatted object literal so diffs stay stable across
 * runs. Runtime regex-compile injections (e.g. `compiled_pattern: RegExp`)
 * are stripped before serialization so they cannot leak into the source.
 */
async function write_permanent_data(permanent: KnownIssue[]): Promise<void> {
  const wire_rules = permanent.map(strip_runtime_only_fields);
  const file: KnownIssuesRegistryFile = {
    schema_version: KNOWN_ISSUES_REGISTRY_SCHEMA_VERSION,
    rules: wire_rules,
  };
  const body =
    "// AUTO-GENERATED by `pnpm sync-permanent-rules` — do not edit by hand.\n" +
    "// Source of truth: .claude/skills/triage-entrypoints/known_issues/registry.json\n" +
    "// CI gate: `pnpm sync-permanent-rules && git diff --exit-code`.\n" +
    "\n" +
    "import type { KnownIssuesRegistryFile } from \"@ariadnejs/types\";\n" +
    "\n" +
    "export const PERMANENT_REGISTRY_FILE: KnownIssuesRegistryFile = " +
    JSON.stringify(file, null, 2) +
    ";\n";
  await fs.writeFile(PERMANENT_DATA_PATH, body, "utf8");
}

async function write_builtins_barrel(rules: readonly KnownIssue[]): Promise<void> {
  const body = render_builtins_barrel(rules);
  await fs.mkdir(path.dirname(BARREL_PATH), { recursive: true });
  await fs.writeFile(BARREL_PATH, body, "utf8");
}

/** Drop runtime-only injections (e.g. `compiled_pattern`) before serializing. */
function strip_runtime_only_fields(issue: KnownIssue): KnownIssue {
  if (issue.classifier.kind !== "predicate") return issue;
  return {
    ...issue,
    classifier: {
      ...issue.classifier,
      expression: strip_compiled_pattern(issue.classifier.expression),
    },
  };
}

/**
 * Walk every node in a predicate tree, returning a structurally-equivalent
 * copy with the runtime-injected `compiled_pattern` field stripped from
 * regex-bearing leaves. Combinators recurse; non-regex leaves pass through
 * unchanged. The exhaustive switch forces a sync-script update whenever a
 * new `PredicateOperator` lands — falling through `default: return expr`
 * would silently leak any future regex-bearing op's `compiled_pattern` into
 * the published slice.
 */
function strip_compiled_pattern(expr: PredicateExpr): PredicateExpr {
  switch (expr.op) {
    case "all":
    case "any":
      return { op: expr.op, of: expr.of.map(strip_compiled_pattern) };
    case "not":
      return { op: "not", of: strip_compiled_pattern(expr.of) };
    case "decorator_matches":
    case "grep_line_regex":
      return { op: expr.op, pattern: expr.pattern };
    case "grep_hit_neighbourhood_matches":
      return { op: expr.op, pattern: expr.pattern, window: expr.window };
    case "diagnosis_eq":
    case "language_eq":
    case "has_capture_at_grep_hit":
    case "missing_capture_at_grep_hit":
    case "resolution_failure_reason_eq":
    case "receiver_kind_eq":
    case "syntactic_feature_eq":
    case "grep_hits_all_intra_file":
    case "definition_feature_eq":
    case "accessor_kind_eq":
    case "has_unindexed_test_caller":
      return expr;
  }
  // Force exhaustiveness: a new `PredicateOperator` lands → tsc compile error
  // here, prompting the sync-script author to decide whether the new op
  // carries a regex (and therefore needs stripping).
  const _exhaustive: never = expr;
  return _exhaustive;
}

async function main(): Promise<void> {
  const { permanent_count, builtin_count } = await sync_permanent_rules();
  console.log(`sync-permanent-rules: ${permanent_count} permanent rules → permanent_data.ts`);
  console.log(`sync-permanent-rules: ${builtin_count} builtin rules → builtins/index.ts`);
}

const invoked_directly =
  import.meta.url === `file://${process.argv[1]}` ||
  fileURLToPath(import.meta.url) === process.argv[1];
if (invoked_directly) {
  main().catch((error) => {
    const message = error instanceof Error ? error.message : String(error);
    console.error(`sync-permanent-rules: ${message}`);
    process.exit(1);
  });
}
