#!/usr/bin/env node
/* eslint-disable no-undef */

const fs = require('fs');
const path = require('path');

// Read package.json
const packageJsonPath = path.join(__dirname, '..', 'package.json');
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));

// Generate version.ts content
const versionContent = `// This file is auto-generated by scripts/update-version.js
// DO NOT EDIT MANUALLY
export const VERSION = "${packageJson.version}";
`;

// Write to version.ts
const versionFilePath = path.join(__dirname, '..', 'src', 'version.ts');
fs.writeFileSync(versionFilePath, versionContent);

console.log(`Updated version.ts to version ${packageJson.version}`);