/**
 * Canonical catalog of Ariadne's known failure modes. Stored on disk as
 * `.claude/skills/self-repair-pipeline/known_issues/registry.json` and consumed
 * by the `auto_classify` pipeline stage and by the triage-curator skill.
 *
 * Orthogonal to the dead-code whitelist read by the `detect_dead_code` Stop
 * hook — that lives at `~/.ariadne/self-repair-pipeline/known_entrypoints/<pkg>.json`
 * and is a separate, human-maintained list of legitimate entry points. The
 * self-repair pipeline never reads or writes that whitelist.
 */

import type { DefinitionFeatureName, SyntacticFeatureName } from "./entry_point.js";

export type KnownIssueStatus = "permanent" | "wip" | "fixed";

export type KnownIssueLanguage = "typescript" | "javascript" | "python" | "rust";

export interface KnownIssueExample {
  file: string;
  line: number;
  snippet: string;
}

export interface KnownIssue {
  /** Canonical identifier, kebab-case. */
  group_id: string;
  title: string;
  description: string;
  status: KnownIssueStatus;
  languages: KnownIssueLanguage[];
  /** Links this issue → work prioritization. Absent when no backlog task exists. */
  backlog_task?: string;
  examples: KnownIssueExample[];
  classifier: ClassifierSpec;
  /**
   * Public-facing classification kind that this rule produces when it matches.
   * Drives the `EntryPointClassification` value returned to library consumers
   * via `Project.get_classified_entry_points()`. Permanent-registry rules
   * carry this; wip rules MAY omit it (defaults to `framework_invoked` keyed
   * by the rule's `group_id`).
   *
   * The registry-side `classifier` field is the *match mechanism* (predicate
   * vs builtin). `classification` is the *user-facing label*. Two distinct
   * concerns; keeping them separate lets a single classifier kind drive
   * different public labels.
   */
  classification?: KnownIssueClassificationMeta;
  // Curator-populated fields — never edited by hand, never used for matching.
  observed_count?: number;
  observed_projects?: string[];
  last_seen_run?: string;
  /** Set by the curator when a classifier's outlier rate breaches the drift threshold. */
  drift_detected?: boolean;
}

/**
 * Metadata about how a registry rule should be reported in
 * `EntryPointClassification`. Decoupled from `EntryPointClassification` so
 * the registry doesn't carry per-match fields (e.g. `protocol: entry.name`)
 * that only exist at evaluation time.
 */
export type KnownIssueClassificationMeta =
  | { kind: "framework_invoked"; framework: string }
  | { kind: "dunder_protocol" }
  | { kind: "test_only" }
  | { kind: "indirect_only" };

export type ClassifierAxis = "A" | "B" | "C";

/**
 * Classifier variants:
 *
 * - `none`      — known failure mode, no automated classifier yet.
 * - `predicate` — hand-authored predicate over the closed DSL. Evaluated by
 *                 `predicate_evaluator`.
 * - `builtin`   — investigator-authored TypeScript function generated by the
 *                 triage-curator into `auto_classify/builtins/check_<group_id>.ts`.
 *                 The orchestrator looks up the function in the generated barrel
 *                 `auto_classify/builtins/index.ts` and calls it directly.
 */
export type ClassifierSpec =
  | { kind: "none" }
  | { kind: "predicate"; axis: ClassifierAxis; expression: PredicateExpr; min_confidence: number }
  | { kind: "builtin"; function_name: string; min_confidence: number };

/**
 * Structured, serialisable predicate DSL over an entry + diagnostics. No eval.
 *
 * Schema validation rejects any `op` value not listed here.
 */
export type PredicateExpr =
  // Combinators
  | { op: "all"; of: PredicateExpr[] }
  | { op: "any"; of: PredicateExpr[] }
  | { op: "not"; of: PredicateExpr }
  // Leaves — call-ref + diagnosis features
  | { op: "diagnosis_eq"; value: string }
  | { op: "language_eq"; value: string }
  | { op: "decorator_matches"; pattern: string; compiled_pattern?: RegExp }
  | { op: "has_capture_at_grep_hit"; capture_name: string }
  | { op: "missing_capture_at_grep_hit"; capture_name: string }
  | { op: "grep_line_regex"; pattern: string; compiled_pattern?: RegExp }
  | { op: "resolution_failure_reason_eq"; value: string }
  | { op: "receiver_kind_eq"; value: string }
  | { op: "syntactic_feature_eq"; name: SyntacticFeatureName; value: boolean }
  // Leaves — grep-hit correlation features
  /** True when every grep_call_site shares entry.file_path (intra-file only). */
  | { op: "grep_hits_all_intra_file"; value: boolean }
  /**
   * True when the pattern is found in any of the `window` lines above at
   * least one grep_call_site. Used for `require()`-indirection detection.
   */
  | { op: "grep_hit_neighbourhood_matches"; pattern: string; window: number; compiled_pattern?: RegExp }
  // Leaves — definition-site features (see DefinitionFeatures)
  | { op: "definition_feature_eq"; name: DefinitionFeatureName; value: boolean }
  | { op: "accessor_kind_eq"; value: "getter" | "setter" | "none" }
  // Leaves — unindexed-test-dir callers
  | { op: "has_unindexed_test_caller"; value: boolean };

/** The exhaustive set of recognised predicate operators. Used by schema validation. */
export const PREDICATE_OPERATORS = [
  "all",
  "any",
  "not",
  "diagnosis_eq",
  "language_eq",
  "decorator_matches",
  "has_capture_at_grep_hit",
  "missing_capture_at_grep_hit",
  "grep_line_regex",
  "resolution_failure_reason_eq",
  "receiver_kind_eq",
  "syntactic_feature_eq",
  "grep_hits_all_intra_file",
  "grep_hit_neighbourhood_matches",
  "definition_feature_eq",
  "accessor_kind_eq",
  "has_unindexed_test_caller",
] as const;

export type PredicateOperator = typeof PREDICATE_OPERATORS[number];

/** In-memory list of known issues. Loaders return this shape regardless of wire format. */
export type KnownIssuesRegistry = KnownIssue[];

/** Current schema version for the on-disk registry file. */
export const KNOWN_ISSUES_REGISTRY_SCHEMA_VERSION = 1 as const;
export type KnownIssuesRegistrySchemaVersion = typeof KNOWN_ISSUES_REGISTRY_SCHEMA_VERSION;

/**
 * Wire format for `registry.json` on disk and for the bundled permanent
 * slice. Carrying `schema_version` separately from the in-memory array shape
 * means future field changes can be detected by loaders without forcing
 * downstream consumers to thread the version through.
 */
export interface KnownIssuesRegistryFile {
  schema_version: KnownIssuesRegistrySchemaVersion;
  rules: KnownIssue[];
}

/**
 * Parse the JSON wire format of `registry.json` and return the inner rule
 * array. Verifies the envelope shape and the `schema_version` field; deep
 * shape validation of individual rules is the loader's responsibility.
 */
export function parse_known_issues_registry_json(raw: string): KnownIssue[] {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (e) {
    const reason = e instanceof Error ? e.message : String(e);
    throw new Error(`registry.json is not valid JSON: ${reason}`);
  }
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    throw new Error("registry.json must be a JSON object with `schema_version` and `rules`");
  }
  const record = parsed as Record<string, unknown>;
  if (record["schema_version"] !== KNOWN_ISSUES_REGISTRY_SCHEMA_VERSION) {
    throw new Error(
      `registry.json: schema_version mismatch (expected ${KNOWN_ISSUES_REGISTRY_SCHEMA_VERSION}, got ${String(record["schema_version"])})`,
    );
  }
  if (!Array.isArray(record["rules"])) {
    throw new Error("registry.json: `rules` must be an array");
  }
  return record["rules"] as KnownIssue[];
}

/**
 * Serialize an in-memory rule array to the canonical on-disk JSON format,
 * wrapping in the `{ schema_version, rules }` envelope and producing a
 * trailing newline so the file diffs cleanly.
 */
export function serialize_known_issues_registry_json(rules: readonly KnownIssue[]): string {
  const file: KnownIssuesRegistryFile = {
    schema_version: KNOWN_ISSUES_REGISTRY_SCHEMA_VERSION,
    rules: [...rules],
  };
  return JSON.stringify(file, null, 2) + "\n";
}
