import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

/** Parent of per-run sub-agent outputs and finalized.json sentinels. */
export const CURATOR_RUNS_DIR = path.join(
  os.homedir(),
  ".ariadne",
  "triage-curator",
  "runs",
);

/** Absolute repo root — same value every script derives. Consumed by get_context_cmd builders. */
export function get_repo_root(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  // src/store/ → src/ → triage-curator/ → skills/ → .claude/ → repo root
  return path.resolve(here, "..", "..", "..", "..", "..");
}

function get_core_classify_dir(): string {
  return path.join(get_repo_root(), "packages", "core", "src", "classify_entry_points");
}

/** Directory in core that holds the rendered builtin classifier source files. */
export function get_core_builtins_dir(): string {
  return path.join(get_core_classify_dir(), "builtins");
}

/** Auto-generated barrel that maps `function_name` → builtin classifier function. */
export function get_core_builtins_barrel_path(): string {
  return path.join(get_core_builtins_dir(), "index.ts");
}

/** Bundled permanent-slice TS module shipped in `@ariadnejs/core`. Regenerated by `pnpm sync-permanent-rules`. */
export function get_permanent_slice_path(): string {
  return path.join(get_core_classify_dir(), "permanent_data.ts");
}

/** Relative path from repo root to the triage-curator scripts/ directory. */
export function get_scripts_rel(): string {
  return path.relative(get_repo_root(), path.join(get_repo_root(), ".claude", "skills", "triage-curator", "scripts"));
}

export function run_output_dir(run_id: string): string {
  return path.join(CURATOR_RUNS_DIR, run_id);
}

/**
 * Sidecar file that the main agent appends to after each
 * `mcp__backlog__task_create` call in Step 4. Maps a created task's
 * `target_registry_group_id` (Ariadne-bug flight) or `signal_library_gap`
 * source `group_id` (signal-library flight) to the resolved `TASK-<N>` id.
 * `link_ariadne_bug_tasks.ts` reads this file to drive registry linkage,
 * so a crash between `task_create` and linkage does not strand the
 * registry row without a backlink — the next run picks up where the
 * previous one stopped.
 */
export function created_task_ids_path(run_id: string): string {
  return path.join(run_output_dir(run_id), "created_task_ids.json");
}

