/**
 * Loader for the bundled permanent-rule slice of the known-issues registry.
 *
 * The full registry (with `wip` and `proposed` rules) lives at
 * `.claude/skills/self-repair-pipeline/known_issues/registry.json` and is the
 * curator's working copy. Core ships only the permanent slice via the
 * `PERMANENT_REGISTRY` TS module — generated by the skill's
 * `pnpm sync-permanent-rules` step. Embedding as TS (rather than a sibling
 * `.json`) keeps the published bundle self-contained: no extra `copy-*`
 * build step, no runtime path discovery, no FS reads.
 *
 * On first call we deep-clone and pre-compile regex patterns onto each
 * predicate node so `predicate_evaluator` can read `compiled_pattern`
 * without re-parsing.
 */

import type { KnownIssue, KnownIssuesRegistry, PredicateExpr } from "@ariadnejs/types";
import { KNOWN_ISSUES_REGISTRY_SCHEMA_VERSION } from "@ariadnejs/types";
import { PERMANENT_REGISTRY, PERMANENT_REGISTRY_SCHEMA_VERSION } from "./registry_permanent";

let permanent_registry_cache: KnownIssuesRegistry | null = null;

/**
 * Loader error surfaced when the bundled slice is corrupt or out of date.
 * Fails loud rather than silently degrading classification: a slice that
 * carries a non-permanent or `kind: "none"` rule indicates the sync script
 * regressed and the next user of the library would mis-classify.
 */
export class PermanentRegistryError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "PermanentRegistryError";
  }
}

export function load_permanent_registry(): KnownIssuesRegistry {
  if (permanent_registry_cache !== null) {
    return permanent_registry_cache;
  }
  if (PERMANENT_REGISTRY_SCHEMA_VERSION !== KNOWN_ISSUES_REGISTRY_SCHEMA_VERSION) {
    throw new PermanentRegistryError(
      `bundled permanent slice schema_version ${PERMANENT_REGISTRY_SCHEMA_VERSION} ` +
        `does not match @ariadnejs/types ${KNOWN_ISSUES_REGISTRY_SCHEMA_VERSION} — ` +
        "regenerate via `pnpm sync-permanent-rules`",
    );
  }
  for (const issue of PERMANENT_REGISTRY) {
    assert_permanent_non_none(issue);
  }
  // Deep-clone so the in-place regex compilation does not mutate the
  // exported module constant (which would defeat HMR / repeated loads).
  const cloned: KnownIssuesRegistry = JSON.parse(JSON.stringify(PERMANENT_REGISTRY));
  for (const issue of cloned) {
    if (issue.classifier.kind === "predicate") {
      compile_regex_in_place(issue.classifier.expression);
    }
  }
  permanent_registry_cache = cloned;
  return cloned;
}

function assert_permanent_non_none(issue: KnownIssue): void {
  if (issue.status !== "permanent") {
    throw new PermanentRegistryError(
      `bundled slice contains non-permanent rule "${issue.group_id}" (status="${issue.status}") — ` +
        "the sync script must filter on status === \"permanent\"",
    );
  }
  if (issue.classifier.kind === "none") {
    throw new PermanentRegistryError(
      `bundled slice contains kind:"none" rule "${issue.group_id}" — ` +
        "the sync script must drop unclassified rules from the slice",
    );
  }
}

function compile_regex_in_place(expr: PredicateExpr): void {
  switch (expr.op) {
    case "all":
    case "any":
      for (const child of expr.of) compile_regex_in_place(child);
      return;
    case "not":
      compile_regex_in_place(expr.of);
      return;
    case "decorator_matches":
    case "grep_line_regex":
    case "grep_hit_neighbourhood_matches":
      // Mutate in place — the registry-load contract documented in the skill
      // is that consumers may read `compiled_pattern` without re-parsing.
      (expr as { compiled_pattern: RegExp }).compiled_pattern = new RegExp(expr.pattern);
      return;
    default:
      return;
  }
}

/**
 * Reset the registry cache. Used by tests that swap the slice at runtime;
 * do not call from production code.
 */
export function reset_permanent_registry_cache_for_tests(): void {
  permanent_registry_cache = null;
}
