/**
 * Bundled permanent slice of the known-issues registry.
 *
 * The data lives in `registry.permanent.json`, regenerated by
 * `pnpm sync-permanent-rules` from
 * `.claude/skills/self-repair-pipeline/known_issues/registry.json`. This
 * module imports the JSON; the file is shipped into `dist/` by the
 * `copy-permanent-registry` script in `package.json` (tsc emits the
 * `require("./registry.permanent.json")` call but does not copy data
 * files). The CI gate (`pnpm check-permanent-rules`) fails when the slice
 * drifts from the registry.
 */

import type { KnownIssue, KnownIssuesRegistry } from "@ariadnejs/types";
import permanent_data from "./registry.permanent.json";

/**
 * Schema version copied verbatim from the source registry by
 * `pnpm sync-permanent-rules`. The core loader cross-checks this against
 * `KNOWN_ISSUES_REGISTRY_SCHEMA_VERSION` from `@ariadnejs/types` to detect
 * a stale slice without re-parsing the JSON.
 */
export const PERMANENT_REGISTRY_SCHEMA_VERSION: number = permanent_data.schema_version;

export const PERMANENT_REGISTRY: KnownIssuesRegistry = permanent_data.rules as KnownIssue[];
