/**
 * Bundled permanent slice of the known-issues registry.
 *
 * The data lives in `permanent_data.ts`, regenerated by
 * `pnpm sync-permanent-rules` from
 * `.claude/skills/triage-entrypoints/known_issues/registry.json`. The
 * generated module is plain TypeScript so tsc emits it into `dist/` as
 * part of the normal build. The CI gate (`pnpm check-permanent-rules`)
 * fails when the slice drifts from the source registry.
 */

import type { KnownIssuesRegistry } from "@ariadnejs/types";
import { PERMANENT_REGISTRY_FILE } from "./permanent_data";

/**
 * Schema version copied verbatim from the source registry by
 * `pnpm sync-permanent-rules`. The core loader cross-checks this against
 * `KNOWN_ISSUES_REGISTRY_SCHEMA_VERSION` from `@ariadnejs/types` to detect
 * a stale slice without re-parsing the data.
 */
export const PERMANENT_REGISTRY_SCHEMA_VERSION: number =
  PERMANENT_REGISTRY_FILE.schema_version;

export const PERMANENT_REGISTRY: KnownIssuesRegistry = PERMANENT_REGISTRY_FILE.rules;
