/**
 * Bundled permanent slice of the known-issues registry.
 *
 * The data lives in `registry.permanent.json` (regenerated by the skill's
 * `pnpm sync-permanent-rules` command from
 * `.claude/skills/self-repair-pipeline/known_issues/registry.json`). This
 * module imports the JSON so tsc compiles a `require("./registry.permanent.json")`
 * into `dist/`; the CI gate (`git diff --exit-code packages/core/src/classify_entry_points/`)
 * fails loud whenever the slice drifts from the registry.
 */

import type { KnownIssuesRegistry } from "@ariadnejs/types";
import permanent_data from "./registry.permanent.json";

/**
 * Schema version copied verbatim from the source registry by
 * `pnpm sync-permanent-rules`. The core loader cross-checks this against
 * `KNOWN_ISSUES_REGISTRY_SCHEMA_VERSION` from `@ariadnejs/types` to detect
 * a stale slice without re-parsing the JSON.
 */
export const PERMANENT_REGISTRY_SCHEMA_VERSION = permanent_data.schema_version as 1;

export const PERMANENT_REGISTRY: KnownIssuesRegistry =
  permanent_data.rules as KnownIssuesRegistry;
