/**
 * Loader for the bundled permanent-rule slice of the known-issues registry.
 *
 * The full registry (with `wip` and `proposed` rules) lives at
 * `.claude/skills/self-repair-pipeline/known_issues/registry.json` and is the
 * curator's working copy. Core ships only the permanent slice as
 * `permanent_data.ts`, regenerated by `pnpm sync-permanent-rules`. Because
 * the slice is a `.ts` module, tsc emits it into `dist/` as part of the normal
 * build — no separate copy step is needed.
 *
 * On first call we structurally-clone the bundled slice and pre-compile each
 * predicate's regex pattern. Cloning is a typed pure function (no JSON
 * round-trip) so non-serializable fields can never be silently dropped.
 */

import type {
  ClassifierSpec,
  KnownIssue,
  KnownIssuesRegistry,
  PredicateExpr,
} from "@ariadnejs/types";
import { KNOWN_ISSUES_REGISTRY_SCHEMA_VERSION } from "@ariadnejs/types";
import { PERMANENT_REGISTRY, PERMANENT_REGISTRY_SCHEMA_VERSION } from "./registry_permanent";

let permanent_registry_cache: KnownIssuesRegistry | null = null;

/**
 * Loader error surfaced when the bundled slice is corrupt or out of date.
 * Fails loud rather than silently degrading classification: a slice that
 * carries a non-permanent or `kind: "none"` rule indicates the sync script
 * regressed and the next user of the library would mis-classify.
 */
export class PermanentRegistryError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "PermanentRegistryError";
  }
}

export function load_permanent_registry(): KnownIssuesRegistry {
  if (permanent_registry_cache !== null) {
    return permanent_registry_cache;
  }
  validate_permanent_slice(PERMANENT_REGISTRY);
  permanent_registry_cache = PERMANENT_REGISTRY.map(clone_with_compiled_pattern);
  return permanent_registry_cache;
}

/**
 * Cross-check the slice against the published schema version and reject
 * non-permanent or `kind: "none"` rules. Pure — no caching or mutation —
 * so tests can call it directly against a synthetic slice.
 */
export function validate_permanent_slice(rules: readonly KnownIssue[]): void {
  if (PERMANENT_REGISTRY_SCHEMA_VERSION !== KNOWN_ISSUES_REGISTRY_SCHEMA_VERSION) {
    throw new PermanentRegistryError(
      `bundled permanent slice schema_version ${PERMANENT_REGISTRY_SCHEMA_VERSION} ` +
        `does not match @ariadnejs/types ${KNOWN_ISSUES_REGISTRY_SCHEMA_VERSION} — ` +
        "regenerate via `pnpm sync-permanent-rules`",
    );
  }
  for (const issue of rules) {
    assert_permanent_non_none(issue);
  }
}

function assert_permanent_non_none(issue: KnownIssue): void {
  if (issue.status !== "permanent") {
    throw new PermanentRegistryError(
      `bundled slice contains non-permanent rule "${issue.group_id}" (status="${issue.status}") — ` +
        "the sync script must filter on status === \"permanent\"",
    );
  }
  if (issue.classifier.kind === "none") {
    throw new PermanentRegistryError(
      `bundled slice contains kind:"none" rule "${issue.group_id}" — ` +
        "the sync script must drop unclassified rules from the slice",
    );
  }
}

/**
 * Return a fresh `KnownIssue` whose predicate expression has `compiled_pattern`
 * pre-attached on every regex-bearing leaf. Pure: callers receive a tree that
 * shares no mutable substructure with `PERMANENT_REGISTRY`, so an HMR reload
 * (or a test that swaps the slice) cannot leak a `RegExp` back into the
 * exported module constant.
 */
function clone_with_compiled_pattern(issue: KnownIssue): KnownIssue {
  return { ...issue, classifier: clone_classifier(issue.classifier) };
}

function clone_classifier(spec: ClassifierSpec): ClassifierSpec {
  if (spec.kind !== "predicate") return { ...spec };
  return { ...spec, expression: clone_expr_with_compiled_pattern(spec.expression) };
}

function clone_expr_with_compiled_pattern(expr: PredicateExpr): PredicateExpr {
  switch (expr.op) {
    case "all":
    case "any":
      return { op: expr.op, of: expr.of.map(clone_expr_with_compiled_pattern) };
    case "not":
      return { op: "not", of: clone_expr_with_compiled_pattern(expr.of) };
    case "decorator_matches":
    case "grep_line_regex":
      return {
        op: expr.op,
        pattern: expr.pattern,
        compiled_pattern: new RegExp(expr.pattern),
      };
    case "grep_hit_neighbourhood_matches":
      return {
        op: expr.op,
        pattern: expr.pattern,
        window: expr.window,
        compiled_pattern: new RegExp(expr.pattern),
      };
    case "diagnosis_eq":
    case "language_eq":
    case "has_capture_at_grep_hit":
    case "missing_capture_at_grep_hit":
    case "resolution_failure_reason_eq":
    case "receiver_kind_eq":
    case "syntactic_feature_eq":
    case "grep_hits_all_intra_file":
    case "definition_feature_eq":
    case "accessor_kind_eq":
    case "has_unindexed_test_caller":
      return { ...expr };
  }
  // Force exhaustiveness: a new `PredicateOperator` lands → tsc compile error
  // here, prompting the loader author to decide whether the new op carries a
  // regex.
  const _exhaustive: never = expr;
  return _exhaustive;
}

/**
 * Reset the registry cache. Used by tests that swap the slice at runtime;
 * do not call from production code.
 */
export function reset_permanent_registry_cache_for_tests(): void {
  permanent_registry_cache = null;
}
