name: Ariadne Self-Analysis Validation

on:
  workflow_dispatch:  # Allow manual triggering
  pull_request:
    paths:
      - 'packages/core/src/**'
      - 'packages/types/src/**'
      
jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Run self-analysis validation
        run: |
          echo "🔍 Running Ariadne self-analysis validation..."
          npx tsx packages/core/agent-validation/ci-validation.ts
          
      - name: Upload validation output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validation-output
          path: packages/core/agent-validation/ariadne-validation-output.yaml
          retention-days: 7